version: "3.8"

services:
  
  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8000:5000
    volumes:
      - ./backend:/backend
    depends_on:
      - db
    networks:
      - prometheus_network


  db:
    container_name: db
    image: postgres:alpine3.19
    ports:
      - 5434:5432
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: banco_de_dados
      POSTGRES_PASSWORD: 123456
    restart: unless-stopped
    networks:
      - prometheus_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - prometheus_network


networks:
  prometheus_network:
    driver: bridge


  
  