scrape_configs:
- job_name: backend
  scrape_interval: 5s
  static_configs:
  - targets:
    - backend:5000


- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - prometheus:9090



